# Generated by Django 3.2.7 on 2021-10-14 23:58

from django.db import migrations
from django.utils import timezone
from random import randint

now = timezone.now()

def populate_db(apps, schema_editor):
	Question = apps.get_model('polls', 'Question')
	q = Question(question_text="What's up?", pub_date=now)

	q.save()
	q.choice_set.create(choice_text='Not much', votes=0)
	q.choice_set.create(choice_text='The sky', votes=0)
	q.choice_set.create(choice_text='Just hacking again', votes=0)
	
	
	q = Question(question_text="Best James Bond Actor", pub_date=now)
	q.save()
	james_bonds = ['Daniel Craig', 'Sean Connery', 'Pierce Brossnan', 'Roger Moore', 'Timoth Dalton']
	for actor in james_bonds:
		q.choice_set.create(choice_text=actor, votes=randint(0, 30))


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
		migrations.RunPython(populate_db)
    ]